version: '3.5'

services:
  app:
    build:
      args:
        user: risk-profile
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    restart: always
    working_dir: /var/www
    networks:
      - risk-profile
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1 #docker network ip.

  webserver:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - risk-profile

networks:
  risk-profile:
    driver: bridge